### ISSUE TITLE
api has been closed

### ISSUE THREAD

**Issue by nchen909** [cckuailong/gitAutoStar#2]
47.95.194.180 may be in debt for a long time... Though it can be visited now, but...
Its api has been closed and I can't post to this uri : "http://" + info.addr + "/api/users/" + info.gs_name + "/status/recommend"

2019/12/27 16:33:17 &{200 OK 200 HTTP/1.1 1 1 map[Connection:[keep-alive] Content-Type:[text/html; charset=utf-8] Date:[Fri, 27 Dec 2019 08:33:17 GMT] Server:[nginx] Set-Cookie:[beegosessionID=8db50b2efdf379239823da85b61e26f3; Path=/; HttpOnly] Vary:[Accept-Encoding]] 0xc000004100 -1 [chunked] false true map[] 0xc000118100 <nil>}
2019/12/27 16:33:17 beegosessionID=XXXXXXXXXXXXXXXXXXXXXX; Path=/; HttpOnly
2019/12/27 16:33:17 &{404 Not Found 404 HTTP/1.1 1 1 map[Connection:[keep-alive] Content-Type:[text/html; charset=utf-8] Date:[Fri, 27 Dec 2019 08:33:18 GMT] Server:[nginx] Vary:[Accept-Encoding]] 0xc00006aa20 -1 [chunked] false true map[] 0xc000160000 <nil>}
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x8 pc=0x6721e3]

goroutine 1 [running]:
github.com/bitly/go-simplejson.(*Json).Array(...)
	C:/study/gitautostar/gitAutoStar/src/github.com/bitly/go-simplejson/simplejson.go:184
main.(*INFO).getGitStarList(0xc00009be78, 0xc0000741d0, 0xc0000741c0, 0xc0000ba1a0)
	C:/study/gitautostar/gitAutoStar/src/gitStar.go:111 +0x303
main.run_star()
	C:/study/gitautostar/gitAutoStar/src/gitStar.go:152 +0x8e
main.main()
	C:/study/gitautostar/gitAutoStar/src/gitStar.go:169 +0x2d

Process finished with exit code 2

Maybe your flask of toapi has been closed. So can you reopen your api or please provide new api address to me? Thanks.

**Comment by cckuailong** [comment]
I’m sorry.  But I don't the manager of the website. Maybe you can use the selenium version of git autostar. (https://github.com/cckuailong/gitAutoStar-py)

**Comment by nchen909** [comment]
oh。。but toapi can be applied to any website by builds or others. So I guess the api might be written by you and  the flask on server is opened to ensure everyone can use this api. So if you are not the controller of this api, how can you found http://47.95.194.180/api ? @cckuailong

**Comment by cckuailong** [comment]
> oh。。but toapi can be applied to any website by builds or others. So I guess the api might be written by you and the flask on server is opened to ensure everyone can use this api. So if you are not the controller of this api, how can you found http://47.95.194.180/api ? @cckuailong

The APIs were public before, but now, the func was closed for some reason. Maybe the pressure of the server, you know.
