### ISSUE TITLE
 GitHub star API is going to be deprecated 

### ISSUE THREAD

**Issue by nchen909** [cckuailong/gitAutoStar#3]
Hello, I recently received an Email noticing GitHub star API is going to be deprecated as follows. Will it affect the usage of this repo?

[Github]Deprecation Notice
You recently used a password to access an endpoint through the GitHub API using Go-http-client/1.1. We will deprecate basic authentication using password to this endpoint soon:

https://api.github.com/user/starred/33cn/chain33

We recommend using a personal access token (PAT) with the appropriate scope to access this endpoint instead. Visit https://github.com/settings/tokens for more information.

Thanks,
The GitHub Team

**Comment by cckuailong** [comment]
Github will use the token to access the API, so the only thing we need to change is:
1. go for <https://github.com/settings/tokens> to apply for a personal access token.
2. fill the git_pwd with your token in the config file
I will update the readme soon later. Thank you for remind me the warning.
